import sacrebleu
import ollama

def calculate_ter(generated_texts, reference_texts):
    """
    Calculate the Translation Edit Rate (TER) score for a set of generated texts against their reference texts.
    
    Args:
    generated_texts (list of str): The texts generated by the model.
    reference_texts (list of str): The reference texts to compare against.
    
    Returns:
    float: The TER score.
    """
    references = [[ref] for ref in reference_texts]  
    ter = sacrebleu.corpus_ter(generated_texts, references)  
    return ter.score

response = ollama.chat(model='falcon:7b', messages=[{'role': 'user', 'content': 'Why is the sky blue?',}])
generated_text = response['message']['content']
print(f"Generated text: {generated_text}")

reference_texts = ["The sky appears blue because of a phenomenon called Rayleigh scattering. When sunlight enters the Earth’s atmosphere, it collides with gas molecules. The gas molecules then scatter the light in all directions. Blue light has shorter wavelengths than other colors in the spectrum, so when it collides with gas molecules, it is scattered more than other colors. This causes most of the blue light to reach the observer’s eye, making it appear blue."]

ter_score = calculate_ter([generated_text], reference_texts)
print(f"TER Score: {ter_score:.2f}")
